import { aumWordmarkSmall } from './art.generated';

/** A greeting for anyone who opens the console. */
export function consoleEasterEgg(): void {
  if (typeof console === 'undefined') return;
  const art = aumWordmarkSmall.lines.join('\n');
  console.log(`%c${art}`, 'color:#3b82f6;font-family:monospace;font-weight:bold;');
  console.log(
    '%cHello, fellow code reader. The ASCII portraits on this site are generated by scripts/ascii.mjs from the real photos, with no runtime image work. Come say hi.',
    'color:#9ca3b0;font-family:monospace;',
  );
}
