import {
  siApple,
  siBun,
  siClaudecode,
  siDocker,
  siElectron,
  siExpress,
  siClaude,
  siGithub,
  siGooglegemini,
  siHono,
  siLenovo,
  siLinux,
  siMongodb,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siPostgresql,
  siQemu,
  siRaspberrypi,
  siRabbitmq,
  siReact,
  siRedis,
  siSocketdotio,
  siSpringboot,
  siTypescript,
  siUbuntu,
} from 'simple-icons';

/** Skill or tool name (as in src/data/skills.ts and profile.build.tools) -> simple-icons brand icon. Skills without one are left out on purpose. */
export const skillIcons: Record<string, { title: string; path: string }> = {
  'Node.js': siNodedotjs,
  TypeScript: siTypescript,
  Express: siExpress,
  'Spring Boot': siSpringboot,
  Bun: siBun,
  'Socket.IO': siSocketdotio,
  PostgreSQL: siPostgresql,
  MongoDB: siMongodb,
  Redis: siRedis,
  RabbitMQ: siRabbitmq,
  'Gemini API': siGooglegemini,
  React: siReact,
  'Next.js': siNextdotjs,
  Electron: siElectron,
  Docker: siDocker,
  nginx: siNginx,
  Linux: siLinux,
  'Claude Code': siClaudecode,
  // Setup page
  Hono: siHono,
  'GitHub CLI': siGithub,
  'Lenovo LOQ': siLenovo,
  'Ubuntu WSL': siUbuntu,
  'Ubuntu Server': siUbuntu,
  'KVM/QEMU': siQemu,
  'nvm / Node.js': siNodedotjs,
  'Raspberry Pi 2': siRaspberrypi,
  'iPhone 12': siApple,
  'Claude Pro': siClaude,
  'Gemini Pro': siGooglegemini,
};
