#!/usr/bin/env node
/**
 * Photo -> ASCII converter. Run it in dev tooling (`npm run ascii`), never in the browser.
 *
 * Reads public/images/*.jpg, crops, resamples to a character grid, maps luminance to a glyph
 * ramp and writes typed data to src/ascii/art.generated.ts. The site only ever ships the
 * finished strings, so there is no runtime image work.
 *
 * Cell geometry: the renderer sets `line-height: 1` and IBM Plex Mono advances 0.6em, so a
 * grid of `cols` x `rows` characters has the aspect (cols * 0.6) / rows. We pick `rows` so
 * that aspect matches the crop exactly.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import figlet from 'figlet';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = resolve(root, 'src/ascii/art.generated.ts');

const GLYPH_ADVANCE = 0.6; // IBM Plex Mono advance width, in em
const LINE_HEIGHT = 1; // em, set by the renderer

/** Light-on-dark ramps: sparse glyphs for shadow, dense glyphs for highlights. */
const RAMPS = {
  sm: ' .:-=+*#%@',
  md: ' .:-=+*#%@',
  lg: ' .,:;-~=+*xX#%&@',
};

/** Crops are in source pixels. Each mirrors how the design frames the photo. */
const ASSETS = [
  {
    id: 'avatar',
    src: 'public/images/aum-portrait.jpg',
    crop: { left: 205, top: 25, width: 250, height: 321 }, // head and collar, tight so the face reads
    focus: { cx: 0.5, cy: 0.42, rx: 0.75, ry: 0.8 },
    sizes: { sm: 38, md: 56, lg: 96 },
  },
  {
    id: 'card',
    src: 'public/images/aum-portrait.jpg',
    crop: { left: 0, top: 31, width: 660, height: 528 }, // 5:4 classic profile card
    focus: { cx: 0.5, cy: 0.5, rx: 0.7, ry: 0.75 },
    sizes: { sm: 50, md: 76, lg: 128 },
  },
  {
    id: 'polaroid',
    src: 'public/images/aum-full.jpg',
    crop: { left: 0, top: 102, width: 900, height: 900 }, // square polaroid window
    focus: { cx: 0.5, cy: 0.5, rx: 0.8, ry: 0.8 },
    sizes: { sm: 30, md: 46, lg: 72 },
  },
  {
    id: 'full',
    src: 'public/images/aum-full.jpg',
    crop: { left: 0, top: 0, width: 900, height: 1200 }, // whole frame, boot screen
    focus: { cx: 0.5, cy: 0.62, rx: 0.8, ry: 0.62 },
    sizes: { sm: 44, md: 70, lg: 110 },
  },
];

const smoothstep = (a, b, x) => {
  const t = Math.min(1, Math.max(0, (x - a) / (b - a)));
  return t * t * (3 - 2 * t);
};

/**
 * Tone pipeline: stretched luminance (light-on-dark, so highlights get the dense glyphs), a small
 * unsharp term so edges stay crisp, and a gentle elliptical fade so the subject leads.
 */
async function toAscii({ src, crop, sizes, focus }, size) {
  const cols = sizes[size];
  const aspect = crop.width / crop.height;
  const rows = Math.round((cols * GLYPH_ADVANCE) / (LINE_HEIGHT * aspect));
  const { data } = await sharp(resolve(root, src))
    .extract(crop)
    .resize(cols, rows, { fit: 'fill', kernel: 'lanczos3' })
    .greyscale()
    .normalise({ lower: 2, upper: 98 })
    .raw()
    .toBuffer({ resolveWithObject: true });

  const at = (x, y) =>
    data[Math.min(rows - 1, Math.max(0, y)) * cols + Math.min(cols - 1, Math.max(0, x))] / 255;
  const ramp = RAMPS[size];
  const lines = [];
  for (let y = 0; y < rows; y += 1) {
    let line = '';
    for (let x = 0; x < cols; x += 1) {
      const lum = at(x, y);
      let mean = 0;
      for (let dy = -1; dy <= 1; dy += 1)
        for (let dx = -1; dx <= 1; dx += 1) mean += at(x + dx, y + dy);
      const edge = Math.max(0, lum - mean / 9) * 1.2;
      const d = Math.hypot((x / cols - focus.cx) / focus.rx, (y / rows - focus.cy) / focus.ry);
      const mask = 1 - smoothstep(0.55, 1, d);
      const v = Math.min(1, (0.9 * lum + edge) * (0.55 + 0.45 * mask));
      line += ramp[Math.min(ramp.length - 1, Math.floor(v * ramp.length))];
    }
    lines.push(line.replace(/\s+$/, ''));
  }
  return { cols, rows, lines };
}

function wordmark(text, font) {
  const lines = figlet
    .textSync(text, { font, horizontalLayout: 'fitted' })
    .replace(/\s+$/gm, '')
    .split('\n');
  while (lines.length && !lines[0]) lines.shift();
  while (lines.length && !lines[lines.length - 1]) lines.pop();
  return lines;
}

const esc = (s) => JSON.stringify(s);
let body = `// GENERATED by scripts/ascii.mjs (npm run ascii). Do not edit by hand.
import type { AsciiArt, AsciiWordmark } from './types';

`;

for (const asset of ASSETS) {
  const variants = {};
  for (const size of Object.keys(asset.sizes)) variants[size] = await toAscii(asset, size);
  body += `export const ${asset.id}Ascii: AsciiArt = {\n  id: ${esc(asset.id)},\n  aspect: ${(asset.crop.width / asset.crop.height).toFixed(4)},\n  variants: {\n`;
  for (const size of Object.keys(variants)) {
    const v = variants[size];
    body += `    ${size}: {\n      cols: ${v.cols},\n      rows: ${v.rows},\n      lines: [\n${v.lines.map((l) => `        ${esc(l)},`).join('\n')}\n      ],\n    },\n`;
  }
  body += '  },\n};\n\n';
}

// accentFrom: the column where the trailing "." starts, so the renderer can tint it.
const dotStart = (text, font) => {
  const whole = wordmark(text, font);
  const dot = wordmark('.', font);
  const wholeW = Math.max(...whole.map((l) => l.length));
  return wholeW - Math.max(...dot.map((l) => (l.trimStart().length ? l.length : 0)));
};
const marks = {
  aumWordmark: {
    lines: wordmark('aum.', 'ANSI Shadow'),
    accentFrom: dotStart('aum.', 'ANSI Shadow'),
  },
  aumWordmarkSmall: {
    lines: wordmark('aum.', 'Standard'),
    accentFrom: dotStart('aum.', 'Standard'),
  },
  notFound: { lines: wordmark('404', 'ANSI Shadow') },
};
for (const [name, { lines, accentFrom }] of Object.entries(marks)) {
  body += `export const ${name}: AsciiWordmark = {\n  cols: ${Math.max(...lines.map((l) => l.length))},${accentFrom === undefined ? '' : `\n  accentFrom: ${accentFrom},`}\n  lines: [\n${lines.map((l) => `    ${esc(l)},`).join('\n')}\n  ],\n};\n\n`;
}

await mkdir(dirname(out), { recursive: true });
await writeFile(out, body.trimEnd() + '\n');
console.log(`wrote ${out}`);
